# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have

CMD: "python -m torch.distributed.launch --nproc_per_node=1 train.py"

HPARAMS: [
  {
   dataset: cityscapes,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   crop_size: "512,1024",
   bs_trn: 3,
   scale_min: 0.5,
   scale_max: 1,
   poly_exp: 2,
   lr: 0.005,
   optimizer: sgd,
   color_aug: 0.25,
   val_freq: 1,
   rmi_loss: false,
   max_epoch: 175,
   default_scale: 1,
   extra_scales: "0.5",
   n_scales: "0.5",
   lr_schedule: poly,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 0.0001,
   snapshot: "/home/rac/Desktop/rhome/rac/semantic-segmentation/logs/train_cityscapes_progressive/ocrnet.HRNet_Mscale_rational-angora_2023.02.11_19.09/last_checkpoint_ep94.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
  },
]
