# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have

CMD: "python -m torch.distributed.launch --nproc_per_node=1 train2.py"

HPARAMS: [
  {
   dataset: cityscapes,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   crop_size: "256,512",
   bs_trn: 6,
   scale_min: 0.25,
   scale_max: 0.5,
   poly_exp: 2,
   lr: 0.005,
   optimizer: sgd,
   color_aug: 0.25,
   val_freq: 1,
   rmi_loss: false,
   max_epoch: 175,
   default_scale: 1,
   extra_scales: "0.125,0.25",
   n_scales: "0.25",
   lr_schedule: poly,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 0.0001,
   snapshot: "ASSETS_PATH/seg_weights/ocrnet.HRNet_industrious-chicken.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
  },
]
